variable "panoptica_access_key" {
  type = string
}

variable "panoptica_secret_key" {
  type = string
}

variable "panoptica_server_url" {
  type = string
}

variable "cluster" {
  type = object({
    context                                         = string # (String) The k8s context name of the cluster
    name                                            = string # (String) The name of cluster in SecureCN
    api_intelligence_dast                           = optional(bool) # (Boolean) Enable API Intelligence DAST integration
    auto_labeling                                   = optional(bool) # (Boolean) Enable auto labeling of Kubernetes namespaces
    cd_pod_template                                 = optional(bool) # (Boolean) Identify pod templates only originating from SecureCN CD plugin
    ci_image_validation                             = optional(bool) # (Boolean) Identify pods only if the image hash matches the value generated by the CI plugin or entered manually in the UI
    connections_control                             = optional(bool) # (Boolean) Enable connections control
    # external_ca (Block List, Max: 1) Use an external CA for this cluster (see below for nested schema)
    external_https_proxy                            = optional(string) # (String) Proxy definitions for outgoing HTTPS traffic from the cluster, if needed
    fail_close                                      = optional(bool) # (Boolean) When enabled, workloads and connections will be blocked in case SecureCN agent is not responding
    hold_application_until_proxy_starts             = optional(bool) # (Boolean) Indicates whether the controller should hold the application until the proxy starts
    inspect_incoming_cluster_connections            = optional(bool) # (Boolean) Enable enforcement and visibility of connections from external IP sources
    # internal_registry (Block List, Max: 1) Use an internal container registry for this cluster (see below for nested schema)
    istio_ingress_annotations                       = optional(map(string)) # (Map of String) If enabling Istio ingress, use Istio these ingress annotation
    istio_ingress_enabled                           = optional(bool) # (Boolean) If installing Istio, use Istio ingress
    istio_version                                   = optional(string) # (String) When installing SecureCN agent deployment, use the already existing Istio deployment
    minimum_replicas                                = optional(number) # (Number) Number of replicas of the portshift-agent to install in the cluster.
    multi_cluster_communication_support             = optional(bool) #(Boolean) Enable multi cluster communication
    multi_cluster_communication_support_certs_path  = optional(string) # (String) Multi cluster certs path. Only valid if multi_cluster_communication_support is true
    orchestration_type                              = optional(string) # (String) Orchestration type of the kubernetes cluster
    persistent_storage                              = optional(bool) # (Boolean) Allow SecureCN agent to save the policy persistently, so it will be available after a restart of the pod. This will Require 128MB of storage for the agent pod.
    restrict_registries                             = optional(bool) # (Boolean) Workload from untrusted registries will be marked as 'unknown'
    service_discovery_isolation                     = optional(bool) # (Boolean) Indicates whether the service discovery isolation is enabled
    # sidecar_resources (Block List, Max: 1) Define resource limits for Istio sidecars (see below for nested schema)
    skip_ready_check                                = optional(bool) # (Boolean) Indicates whether the cluster installation should be async
    spec_reconstruction                             = optional(bool) # (Boolean) Indicates whether the OpenAPI specification reconstruction is enabled
    tls_inspection                                  = optional(bool) # (Boolean) Indicates whether the TLS inspection is enabled
    token_injection                                 = optional(bool) # (Boolean) Indicates whether the token injection is enabled
    trace_analyzer                                  = optional(bool) # (Boolean) Indicates whether the trace analyzer is enabled
    tracing_support                                 = optional(bool) # (Boolean) Indicates whether to install tracing support, enable for apiSecurity accounts.
  })
}
